name: Conventional PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
#           edited = edits to PR
#           opened = a new pr for a new branch
#           reopened = a closed PR is reopened
#           synchronize = new commits (needed to be a status checker)


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
